## 배열 사칙연산

In [2]:
import numpy as np 
print(np.__version__)

1.22.2


In [21]:
a = np.array([[1,2,3],[2,3,4]])
b = np.array([[5,6,2],[9,8,7]])

print(a)
print(b)

[[1 2 3]
 [2 3 4]]
[[5 6 2]
 [9 8 7]]


In [22]:
print(a + b)
print(np.add(a, b))

[[ 6  8  5]
 [11 11 11]]
[[ 6  8  5]
 [11 11 11]]


In [23]:
print(a - b)
print(np.subtract(a, b))

[[-4 -4  1]
 [-7 -5 -3]]
[[-4 -4  1]
 [-7 -5 -3]]


In [24]:
print(a * b)
print(np.multiply(a, b))

[[ 5 12  6]
 [18 24 28]]
[[ 5 12  6]
 [18 24 28]]


In [25]:
print(a / b)
print(np.divide(a, b))

[[0.2        0.33333333 1.5       ]
 [0.22222222 0.375      0.57142857]]
[[0.2        0.33333333 1.5       ]
 [0.22222222 0.375      0.57142857]]
