## Transpose

In [1]:
import numpy as np
np.__version__

'1.22.2'

In [26]:
arr = np.arange(8).reshape(2, 4)
print(arr, "\n")
print(arr.shape)
print("---")
arr = arr.T
print(arr, "\n")
print(arr.shape)
print("---")
arr = arr.transpose()
print(arr, "\n")
print(arr.shape)

[[0 1 2 3]
 [4 5 6 7]] 

(2, 4)
---
[[0 4]
 [1 5]
 [2 6]
 [3 7]] 

(4, 2)
---
[[0 1 2 3]
 [4 5 6 7]] 

(2, 4)


## 정렬

In [31]:
arr = np.array([
    [3,1,2], 
    [4,2,10], 
    [5,3,2]
])

print(arr)
print(arr.shape)
print("---")
print(np.sort(arr))
print("---axis=1---")
print(np.sort(arr, axis=1))
print("---axis=0---")
print(np.sort(arr, axis=0))

[[ 3  1  2]
 [ 4  2 10]
 [ 5  3  2]]
(3, 3)
---
[[ 1  2  3]
 [ 2  4 10]
 [ 2  3  5]]
---axis=1---
[[ 1  2  3]
 [ 2  4 10]
 [ 2  3  5]]
---axis=0---
[[ 3  1  2]
 [ 4  2  2]
 [ 5  3 10]]


## 데이터 합치기

In [50]:
a = np.arange(6).reshape(2,3)
b = np.ones((2, 3))

print(a, "\n")
print(b, "\n")

print("hstack\n", np.hstack((a,b)), "\n")
print(np.hstack((a,b)).shape, "\n")
print("vstack\n", np.vstack((a,b)), "\n")
print(np.vstack((a,b)).shape, "\n")
print("concatenate\n", np.concatenate((a,b)), "\n")
print(np.concatenate((a,b)).shape)
print("concatenate axis=None\n", np.concatenate((a,b), axis=None), "\n")
print(np.concatenate((a,b), axis=None).shape)

[[0 1 2]
 [3 4 5]] 

[[1. 1. 1.]
 [1. 1. 1.]] 

hstack
 [[0. 1. 2. 1. 1. 1.]
 [3. 4. 5. 1. 1. 1.]] 

(2, 6) 

vstack
 [[0. 1. 2.]
 [3. 4. 5.]
 [1. 1. 1.]
 [1. 1. 1.]] 

(4, 3) 

concatenate
 [[0. 1. 2.]
 [3. 4. 5.]
 [1. 1. 1.]
 [1. 1. 1.]] 

(4, 3)
concatenate axis=None
 [0. 1. 2. 3. 4. 5. 1. 1. 1. 1. 1. 1.] 

(12,)
