## NumPy 라이브러리 불러오기 및 버전 확인

In [2]:
import numpy as np 
print(np.__version__)

1.22.2


In [3]:
list_01 = [1, 2, 3]
list_02 = [4, 5, 6]

list_01 + list_02

[1, 2, 3, 4, 5, 6]

In [4]:
array_01 = np.array(list_01)
array_02 = np.array(list_02)
array_01 + array_02

array([5, 7, 9])

## 배열의 차원

In [5]:
array_01.ndim

1

In [6]:
array_2d = np.array([[1, 2], [2, 1]])
print(array_2d, "\n")
print("차원 수: ", array_2d.ndim)

[[1 2]
 [2 1]] 

차원 수:  2


In [7]:
array_2d.shape

(2, 2)

In [8]:
array_2d.dtype

dtype('int32')

## 배열 생성

In [12]:
x = np.array([[1, 2], [2, 1]], dtype=np.float64)

print(x, "\n")
print(x.dtype)

[[1. 2.]
 [2. 1.]] 

float64


In [13]:
array_1d = np.arange(10)
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
array_2d = np.arange(10).reshape(2, 5)
print(array_2d, "\n")
print(array_2d.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]] 

(2, 5)


In [16]:
array_2d = np.arange(10).reshape(2, 4)

ValueError: cannot reshape array of size 10 into shape (2,4)

In [18]:
array_3d = np.arange(8).reshape(2, 2, 2)
print(array_3d, "\n")
print(array_3d.shape)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] 

(2, 2, 2)


In [20]:
array_zeros  = np.zeros((2, 3))
print(array_zeros , "\n")
print(array_zeros .dtype)
print(array_zeros .shape)

[[0. 0. 0.]
 [0. 0. 0.]] 

float64
(2, 3)


In [21]:
array_one = np.ones((2, 3))
print(array_one, "\n")
print(array_one.dtype)
print(array_one.shape)

[[1. 1. 1.]
 [1. 1. 1.]] 

float64
(2, 3)


In [26]:
np.linspace(0, 20, num= 5)

array([ 0.,  5., 10., 15., 20.])

In [29]:
np.random.random((2,3))

array([[0.85598088, 0.05019068, 0.64870848],
       [0.59538304, 0.20327078, 0.27801502]])