## 배열 사칙연산

In [2]:
import numpy as np 
print(np.__version__)

1.22.2


In [21]:
a = np.array([[1,2,3],[2,3,4]])
b = np.array([[5,6,2],[9,8,7]])

print(a)
print(b)

[[1 2 3]
 [2 3 4]]
[[5 6 2]
 [9 8 7]]


In [22]:
print(a + b)
print(np.add(a, b))

[[ 6  8  5]
 [11 11 11]]
[[ 6  8  5]
 [11 11 11]]


In [23]:
print(a - b)
print(np.subtract(a, b))

[[-4 -4  1]
 [-7 -5 -3]]
[[-4 -4  1]
 [-7 -5 -3]]


In [24]:
print(a * b)
print(np.multiply(a, b))

[[ 5 12  6]
 [18 24 28]]
[[ 5 12  6]
 [18 24 28]]


In [25]:
print(a / b)
print(np.divide(a, b))

[[0.2        0.33333333 1.5       ]
 [0.22222222 0.375      0.57142857]]
[[0.2        0.33333333 1.5       ]
 [0.22222222 0.375      0.57142857]]


## 집계함수

In [4]:
array_2d = np.arange(1, 16).reshape(3, 5)
array_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [9]:
print("sum() : ", array_2d.sum())
print("sum(axis=0) : ", array_2d.sum(axis=0))
print("sum(axis=1) : ", array_2d.sum(axis=1))

sum() :  120
sum(axis=0) :  [18 21 24 27 30]
sum(axis=1) :  [15 40 65]


In [10]:
print("mean() : ", array_2d.mean())
print("mean(axis=0) : ", array_2d.mean(axis=0))
print("mean(axis=1) : ", array_2d.mean(axis=1))

mean() :  8.0
mean(axis=0) :  [ 6.  7.  8.  9. 10.]
mean(axis=1) :  [ 3.  8. 13.]


In [13]:
print("min() : ", array_2d.min())
print("min(axis=0) : ", array_2d.min(axis=0))
print("min(axis=1) : ", array_2d.min(axis=1))
print("---")
print("max() : ", array_2d.max())
print("max(axis=0) : ", array_2d.max(axis=0))
print("max(axis=1) : ", array_2d.max(axis=1))

min() :  1
min(axis=0) :  [1 2 3 4 5]
min(axis=1) :  [ 1  6 11]
---
max() :  15
max(axis=0) :  [11 12 13 14 15]
max(axis=1) :  [ 5 10 15]


In [12]:
print("max() : ", array_2d.max())
print("max(axis=0) : ", array_2d.max(axis=0))
print("max(axis=1) : ", array_2d.max(axis=1))

max() :  15
max(axis=0) :  [11 12 13 14 15]
max(axis=1) :  [ 5 10 15]
