## NumPy 조건식 - np.where

In [2]:
import numpy as np
print(np.__version__)

1.22.2


In [4]:
a = np.arange(5)
np.where(a < 3, a, 100 * a)

array([  0,   1,   2, 300, 400])

## 원리

In [5]:
boolArr = a < 3
print(boolArr)
np.where(boolArr, a, 100 * a)

array([ True,  True,  True, False, False])

In [9]:
boolArr2 = np.array([True, True, True, False, False])
np.where(boolArr2, a, 100 * a)

array([  0,   1,   2, 300, 400])

In [19]:
arr = np.arange(16).reshape(4, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
np.where(arr < 5, arr, arr * 10)

array([[  0,   1,   2,   3],
       [  4,  50,  60,  70],
       [ 80,  90, 100, 110],
       [120, 130, 140, 150]])

In [24]:
arr[np.where(arr < 5)]

array([0, 1, 2, 3, 4])

## NumPy 조건식 - np.select

In [26]:
arr = np.arange(10)
print(arr)
condlist   = [arr < 3, arr > 7]
choicelist = [arr * 2, arr * 100]
np.select(condlist, choicelist)

[0 1 2 3 4 5 6 7 8 9]


array([  0,   2,   4,   0,   0,   0,   0,   0, 800, 900])